### ISSUE TITLE
Release schedule for dropping 2.7 and v1.0.0

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#105]
The fall of 2019 is here and we can finally drop Python 2.7 (as we had promised). We already have #100 ready to be merged do to just that. We probably shouldn't drop 2.7 without a big warning and we have #97 that works on 2.7 but still hasn't been released. Here is a tentative schedule for the next 2 releases:

* Make a 0.6.0 release now (before merging #100). It will include #97 and update the warning message to say that this is the last release supporting 2.7 (a PR adding this message is welcome). This version is pretty stable and we haven't broken backwards compatibility in a while.
* After the release, merge #100 (maybe update warnings).
* Release 1.0.0 :confetti_ball:  between now and the end of 2019 with support for Python 3.5+ (and any new features/fixes implemented until then). Our API is pretty stable and we've been good about retaining backwards compatibility. The downloaders and processors mean that Pooch is easily extensible.

Of course, all of this is up for debate and I'm open to suggestions/critique.

**Comment by leouieda** [comment]
Another idea: try to get a JOSS paper for our 1.0.0 release. I hadn't considered this since it seemed like it would be out of scope for JOSS but tqdm (the progress bar generator) has a JOSS paper so we probably could get one.

**Comment by prisae** [comment]
Out of interest - do you know anyone who ever used it with Python 2.7? (Given it is a young-ish project)

**Comment by leouieda** [comment]
We added 2.7 compatibility so MetPy could adopt Pooch and added back 3.5 support for scikit-image. So there are potentially quite a few indirect uses (at least the 2.7 packages get downloaded quite a bit https://anaconda.org/conda-forge/pooch/files).

**Comment by prisae** [comment]
Fair enough... The end is close... :-D

**Comment by leouieda** [comment]
Alright, I think it's safe to move forward with this plan :confetti_ball:

**Comment by hugovk** [comment]
On a similar topic, Matplotlib, scikit-learn, IPython, Jupyter, yt, SciPy, NumPy, and scikit-image have agreed:

* ["NEP 29 — Recommend Python and Numpy version support as a community policy standard"](https://numpy.org/neps/nep-0029-deprecation_policy.html#nep-29-recommend-python-and-numpy-version-support-as-a-community-policy-standard)

Where:

> This NEP recommends that all projects across the Scientific Python ecosystem adopt a common “time window-based” policy for support of Python and NumPy versions. Standardizing a recommendation for project support of minimum Python and NumPy versions will improve downstream project planning.

For example, they suggest:

> This project supports:
> 
> * All minor versions of Python released 42 months prior to the project, and at minimum the two latest minor versions.
> * All minor versions of  `numpy`  released in the 24 months prior to the project, and at minimum the last thee minor versions.

### Support Table

Date | Python | NumPy
-- | -- | --
Jan 07, 2020 | 3.6+ | 1.15+
Jun 23, 2020 | 3.7+ | 1.15+
Jul 23, 2020 | 3.7+ | 1.16+
Jan 13, 2021 | 3.7+ | 1.17+
Jul 26, 2021 | 3.7+ | 1.18+
Dec 26, 2021 | 3.8+ | 1.18+

### Drop Schedule

```
On next release, drop support for Python 3.5 (initially released on Sep 13, 2015)
On Jan 07, 2020 drop support for Numpy 1.14 (initially released on Jan 06, 2018)
On Jun 23, 2020 drop support for Python 3.6 (initially released on Dec 23, 2016)
On Jul 23, 2020 drop support for Numpy 1.15 (initially released on Jul 23, 2018)
On Jan 13, 2021 drop support for Numpy 1.16 (initially released on Jan 13, 2019)
On Jul 26, 2021 drop support for Numpy 1.17 (initially released on Jul 26, 2019)
On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)
```

The idea is these are the minimums, and to reduce maintenance burden on scientific projects, allowing them to worry less about dropping older Python versions, even if they're still supported by CPython itself.

**Comment by leouieda** [comment]
Thanks for pointing out that NEP! This is great and we should adopt something like across our projects. Makes it less arbitrary and easier to communicate and plan. Great stuff, Hugo!

**Comment by leouieda** [comment]
I'll make a 0.7.0 release now to include some of the new features that have been merged since 0.6.0. This will be our first Python 3 only release and will be a good chance to convert the conda-forge feedstock to noarch before we go for 1.0. It would be best to wait for #115 before doing 1.0 since it breaks compatibility slightly.

**Comment by leouieda** [comment]
Alright! We're since dropped Python 2.7, switched from `warnings` to `logging` (thanks @danshapero), and published our JOSS paper. I'd say we're ready for 1.0.0. 

**Any objections or outstanding issues to resolve before tagging the release?**

**Comment by leouieda** [comment]
Alright, since there seem to be no objections I'm merging in #139 and tagging 1.0 :tada:
