### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#112]
I hadn't been considering getting a JOSS paper for Pooch because I thought it wouldn't qualify as "research software". But I just noticed that [tqdm has a JOSS paper](https://joss.theoj.org/papers/10.21105/joss.01277), so I think we can make a case for Pooch. After all, other research software would cite Pooch in their papers (ideally). **What do others think? Is this worth pursuing?**

The criteria for authorship that seems reasonable to me would be:

1. Have contributed code or documentation to Pooch beyond typo fixes 
2. Read/edit the JOSS paper and give their :+1:

This would basically mean anyone [listed on Github](https://github.com/fatiando/pooch/graphs/contributors) that at least reads and OKs the paper. 

As for the order, we could go with the GitHub contributor order (I think it's by number of commit?), and do alphabetical for a tie break. But I'm not entirely sure how to proceed with this one. Any input would be welcome.

Right now, potential authors would be me @santisoler @remram44 @hugovk @matthewturk @jrleeman @matthewturk @danshapero. If any of you are interested, please reply to this thread with your consent, affiliation, and ORCID. Also, whether you think it's worth submitting (the paper itself will take ~1h to write copying from our docs).

**Comment by matthewturk** [comment]
I think it's a good idea, I'd be happy to help, and I also want to
contribute more to Pooch in the future.  I'm 0000-0002-5294-0198, and my
affiliation is the University of Illinois at Urbana-Champaign.

**Comment by remram44** [comment]
Happy to help! I think it's worth submitting, we know of academics using it. I'm 0000-0002-0524-2282 @ New York University.

**Comment by santisoler** [comment]
I think we should submit. Although Pooch is not as a big scientific software, it's very used among other research projects, so I think it would be nice if they have a paper to cite.

My ORCID: [0000-0001-9202-5317](https://orcid.org/0000-0001-9202-5317)
Affiliation: Instituto Geofísico Sismológico Volponi, UNSJ and CONICET, Argentina (both of them should be included, but you can reduce the first one by its acronym: IGSV)

PS: I agree with the contributors order, just remember to ignore @fatiando-bot. AIs don't get the opportunity to publish... yet :robot:

**Comment by danshapero** [comment]
I think it's a good idea! Also an opportunity to talk about how automating scientific workflows helps move towards easier reproducibility, that sort of thing.

ORCID: 0000-0002-3651-0649
Affiliation: Polar Science Center, University of Washington Applied Physics Lab

**Comment by leouieda** [comment]
Alright, I'll got ahead and get a JOSS paper started!

**Comment by hugovk** [comment]
> PS: I agree with the contributors order, just remember to ignore @fatiando-bot. AIs don't get the opportunity to publish... yet 🤖

Or do they?! https://github.com/NaNoGenMo/2019 :)

**Comment by santisoler** [comment]
> > PS: I agree with the contributors order, just remember to ignore @fatiando-bot. AIs don't get the opportunity to publish... yet robot
> 
> Or do they?! https://github.com/NaNoGenMo/2019 :)

Not even Isaac Asimov could see himself being potentially replaced by bots.
Now I think we should ask @fatiando-bot if they wants to be included on the authors list (I'm a little bit afraid of retaliation in the near future).

**Comment by andersy005** [comment]
@leouieda, 

My ORCID: [0000-0001-6583-571X](https://orcid.org/0000-0001-6583-571X)
Affiliation: The US National Center for Atmospheric Research
