### ISSUE TITLE
Use logging instead of warnings for user feedback

### ISSUE THREAD

**Issue by danshapero** [fatiando/pooch#114]
**Description of the desired feature**

Pooch currently uses warnings to give feedback to users when a file is being downloaded, an archive unpacked, etc. The logging module from the Python standard library is a better fit for this purpose.

* More easily adjust how important the feedback is -- downloading a file is information, not having permission to create a destination directory is a warning or error
* Users can choose to silence feedback from pooch without silencing warnings from other libraries

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
@danshapero since this would break backward compatibility (in case users relied on Pooch raising warnings), we should leave it for 1.0.

**Comment by leouieda** [comment]
@dopplershift since MetPy is our main user right now, do you think this change would break anything for you? Would it be helpful to have this?

**Comment by dopplershift** [comment]
I don’t think that would create any problems for MetPy. We in general use both warnings and logging. The rationale we use to decide which one in a given case is:
- Use warnings when the user’s own code is doing something questionable and they can control
- Use logging to indicate what’s going on with IO or other operations that the user has no control over.
