### ISSUE TITLE
How do you pull data from master?

### ISSUE THREAD

**Issue by achapkowski** [fatiando/pooch#146]
I wanted to use this package to just pull down data from a separate repository, so having it just pull from master is fine.  What I set version='master', I get an error.  

Any ideas how to get around this?

**Comment by leouieda** [comment]
Hi @achapkowski you could omit the `version` argument and pass the url to master directly to `base_url`:

```python
pooch.create(
    path=pooch.os_cache("mypackage"),
    base_url="https://github.com/myproject/mypackage/raw/master/data/",
    env="MYPACKAGE_DATA_DIR",
    ...
)
```

**Comment by achapkowski** [comment]
That's what I did, but I didn't know if that was the correct thing to do.

**Comment by leouieda** [comment]
Oh right, sorry I miss read your question. The `version` has to be an actual version number following [PEP440](https://www.python.org/dev/peps/pep-0440/). Pooch will use `master` is this version is a "development" release like `1.2.0.dev10` or something like that. But in your case, it seems that you always want to pull from master, right?

**Comment by achapkowski** [comment]
Thanks for the help.  I was able to use the package to build: https://github.com/achapkowski/spatial-pooch

**Comment by leouieda** [comment]
Awesome! I'll keep an eye on the package
