### ISSUE TITLE
Create a function to fetch a single file

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#147]
**Description of the desired feature**

Consider the following use case: 

> I'm a scientist/educator writing a notebook and I need to get data from this one file on the internet. I'm on Jupyter Lab, possibly on a remote server. I don't know the hash of the file and don't need to download many files, just this one. I want the file to be cached locally and not downloaded multiple times. After the first download, I want to set the hash so that I can make sure future runs of the notebook use the same version of the data. 

Right now, if you want to use Pooch for that you need to write this code:

```python
from unittest import mock

url = "https://www.ngdc.noaa.gov/mgg/ocean_age/data/2008/grids/age/age.3.6.nc.bz2"
remote_file = url.split("/")[-1]

fname = pooch.create(
    path=pooch.os_cache("meh"), 
    base_url="", 
    registry={remote_file: mock.ANY}, 
    urls={remote_file: url}
).fetch(remote_file)

print(pooch.file_hash(fname))
# Copy and paste the hash in the registry above for future runs.
```
There is a lot of repetition and feels like a hack. The same thing in fsspec would look like:

```python
# files is a not-yet-open OpenFile object. The "with" context actually opens it
with fsspec.open(url, mode="r") as f:
    # Read in the data
```

which is much more readable but it doesn't seem to cache automatically (requiring further setup) and doesn't have a hash checking mechanism (at least not that I could find in the docs).

**Proposal**

Add a function `pooch.retrieve` that would make the code above:

```python
fname = pooch.retrieve(url, hash=None)
# hash of downloaded file logged to screen and copy+pasted above for future runs
```

* Automatically cache to a `pooch.os_cache("pooch")` location without further setup.
* File names would be set to a short hash of the file content to make sure no overwriting happens. 
* The return is the file name only, keeping with the pooch way of not trying to do anything fancy. 
* Automatically printing out the hash makes it easier to download first then make sure future downloads are the same.
* Cache location and file name can be set by user if desired.
* Function takes `downloader` and `processor` arguments like `pooch.Pooch.fetch`.

This makes it easy to have all the features of Pooch for single file downloads in very little code.

The name `pooch.fetch` is nicer but it may cause confusion with `pooch.Pooch.fetch` so `retrieve` is a good alternative.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by santisoler** [comment]
A function like this could help to tackle #130 through a simple gallery example.

For example, supose we have the urls of a large number of files that we want to automatically download just to compute their hashes and then build a registry file for future usage through Pooch.
So, we could create the registry file using the proposed functions like this:
```python
import pooch

urls = [...]  # list containing the urls
filenames = [...]  # list containing the filenames used to save the downloaded files

with open("registry.txt", "w") as registry:
    for fname, url in zip(filenames, urls):
        file_path = pooch.retrieve(url, fname=fname)
        hash = pooch.file_hash(file_path)
        registry.write(f"{name} {hash} {url}\n")
```

Maybe we could add an optional argument to `pooch.retrieve` to avoid printing the hash.

**Comment by leouieda** [comment]
> Maybe we could add an optional argument to pooch.retrieve to avoid printing the hash.

No need: https://www.fatiando.org/pooch/latest/usage.html#adjusting-the-logging-level

**Comment by santisoler** [comment]
You're right! We should add the lines for reducing the verbose on the example I proposed.

**Comment by leouieda** [comment]
After #149 we'll also need to refactor out the `Pooch.fetch` code that does the temp file creation, sanity checks, cleanup, hash algorithm determination, etc.
