### ISSUE TITLE
SFTP Downloader

### ISSUE THREAD

**Issue by andersy005** [fatiando/pooch#155]
**Description of the desired feature**

A while ago, we added an FTP Downloader to pooch. I've been wondering whether it would reasonable to add an `SFTP Downloader` as well. For SSH Authentication, I am thinking that we could use [paramiko](https://github.com/paramiko/paramiko). 

**Are you willing to help implement and maintain this feature?** Yes/No

Yes

In case there's no demand/interest for this feature, I am happy to wait until there is a need.

**Comment by leouieda** [comment]
Hi @andersy005 thanks for suggesting this :+1: I wasn't aware of paramiko. 

Is this something you need right now or in the future? If not, then it might be best to wait and see if there is a need first before adding it. Otherwise, go right ahead :slightly_smiling_face:

**Comment by luke-gregor** [comment]
I'm happy to contribute to this too. I've been working on something similar, but really like the approach Pooch takes. 
I've been using `pysftp` which is a wrapper around `paramiko`. 
Should be quite easy if we just use the FTP downloader as a template.
