### ISSUE TITLE
Custom URL Example

### ISSUE THREAD

**Issue by achapkowski** [fatiando/pooch#164]
If my data is being hosted here: https://www.arcgis.com/sharing/rest/content/items/ae25571c60d94ce5b7fcbf74e27c00e0/data

The result is a zipfile.  

Also, I do not know the sha/md5.

Can I use Pooch to manage this type of data?  Can I create a registry.txt for these types of data?

**Comment by santisoler** [comment]
Hi @achapkowski.

For sure, Pooch can manage to download a zip file, cache and decompress it, even if you don't have its hash.

If you don't know the hash, you can make use of the shiny new [`pooch.retrieve`](https://www.fatiando.org/pooch/latest/retrieve.html) function. It allows you to bypass the hash check, so you can download and cache your data files even if you don't have the hash. After downloading for the first time, the hash will be computed and reported to you. We **highly recommend to keep this hash** and use it on later downloads of the file, so the hash check should be bypassed only the first time we download.
After you downloaded the file and computed its hash, you can then create a `registry.txt` file for it.

Regarding the zip compression, you can make use of the [`Unzip`](https://www.fatiando.org/pooch/latest/api/generated/pooch.Unzip.html#pooch.Unzip) processor. It should be passed as argument to [`Pooch.fetch`](https://www.fatiando.org/pooch/latest/api/generated/pooch.Pooch.html#pooch.Pooch.fetch) method.

Hope this answers your questions.
If Pooch documentation is not clear or lacks some explanations or examples, please let us know so we can improve it.

**Comment by achapkowski** [comment]
How would the registry.txt file look in this case then?

**Comment by santisoler** [comment]
Here you have an example of a registry file with custom urls: https://www.fatiando.org/pooch/latest/usage.html#multiple-urls
