### ISSUE TITLE
Finer control over the extraction paths

### ISSUE THREAD

**Issue by soupault** [fatiando/pooch#169]
**Description of the desired feature**

Currently, when the user downloads and unpacks an archive, e.g. with this code:

```
data_0 = pooch.create(
    path=SOME_PATH,
    base_url=SOME_URL,
    registry={"d1.tar": None, },
)

def fetch_data_0():
    download = pooch.HTTPDownloader()
    unpack = pooch.Untar()

    for item in ("d1.tar", ):
        _ = data_0.fetch(
            item,
            processor=unpack,
            downloader=download)
```

the archive is extracted into `SOME_PATH/d1.tar.untar/ARCHIVE_FILES`.

I think it would be great to have a possibility:
1. (preferred) to do flat unpacking, such that the files are put into `SOME_PATH/ARCHIVE_FILES`
2. to change the `suffix` in the preprocessor, e.g. to have `SOME_PATH/d1.tar/ARCHIVE_FILES`. I understand that this option may be challenging when multiple preprocessors are chained, since they, probably, look for the intermediate directories named in a certain way.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
@soupault number 2 might be challenging since we keep the archive to check for updates or if we need to download (since the downloader doesn't know about the unpacked files). So we need to have a different file name. We could add the option to choose the suffix, though.

Number 1 might also be problematic because of the possibility for conflicting names. For example, if you have a `image.png` file and an archive `images.zip` that has a file with same name, we would overwrite the file. That would trigger a download next time `image.png` is requested (since the hash wouldn't match). And then the next time `images.zip` is requested there wouldn't be a download (since the archive hasn't changed) but the returned `image.png` would be the wrong image. So keeping things in separate folders is a safety measure against that.

**Comment by soupault** [comment]
>So keeping things in separate folders is a safety measure against that.

I completely agree with this and do not propose to change the default behaviour. I have been merely thinking about having this as an optional mode, since it is quite a popular one and is implemented in many archive managers. With flat archive containing the files, it can, indeed, be confusing. However, for archives that ship the contents in a folder (i.e. created from a folder, which is very common use case), I believe, that is a valid operating mode.

If you do not see this as a part of the library, that is perfectly fine. I am currently solving this by a custom processor. Perhaps, as an alternative solution, it would make sense to refine and fix the processor API, and allow users to conveniently plug in their custom processors.

**Comment by leouieda** [comment]
@soupault one way to do this safely would be to change the extraction code here https://github.com/fatiando/pooch/blob/master/pooch/processors.py#L118 to first check if any of the files already exist in the directory. If it does, then the processor can raise an exception warning of this. That would avoid the case I outlines above and allow flat unpacking. I'm not against adding this feature if we can find a way to do it relatively safely.

> Perhaps, as an alternative solution, it would make sense to refine and fix the processor API, and allow users to conveniently plug in their custom processors.

Could you elaborate? Do you mean a way to extend the existing processors?

**Comment by leouieda** [comment]
I've been thinking about this a bit in the context of #175. If we want to be able to clear the cache correctly, including unpacked files, the `Pooch` instance needs to know about them somehow. One way of doing that is to have the processors register any extra files created with the instance (they know about it through the `pooch` argument they receive. This could be a dict attribute in `Pooch` that has registry entries as keys and a list of extra file paths generated. This would be a way to allow more control over unpacking and a way to clear the cache properly.

**Comment by leouieda** [comment]
@soupault just a quick update: we had some discussion in #203 and agreed that it's OK to risk conflicting files if we give users ample warning about it in the docs.

So if you still want to go ahead, it would be great to have this feature in `Untar` and `Unzip`. Perhaps a boolean argument `flat=False` to control wether we unpack to a folder of do a flat unpack into the Pooch cache folder. What do you think?

**Comment by leouieda** [comment]
PR #224 adds the ability to set a custom unpacking folder, which would solve some of the requested features here (control the placement of archive members). You could even do a flat unpacking by passing in `"."` as the folder (though we have not tested this).

Unfortunately, I don't see a good way around deleting the original file without significant changes in how Pooch handles the downloads.

@soupault if you're satisfied with these changes, then please go ahead and close this issue. Feel free to keep it open if there is anything else you want to bring up or ways to improve this functionality.

**Comment by soupault** [comment]
Hi @leouieda ,
Sorry, I somehow missed your earlier messages... The solution implemented by @drammock works perfectly for my case. I have just checked and it works smoothly.

As for deleting the original files, I think the most reliable approach would be to create a (hidden) file (e.g. `.pooch.cache`) tracking all the extracted contents. But that would be, obviously, quite a notable and likely undesirable API change. I believe the current implementation is more optimal.

Thank you again!
