### ISSUE TITLE
Comments in registry file?

### ISSUE THREAD

**Issue by mathause** [fatiando/pooch#176]
It could be worthwhile to support comments in registry files. For simplicity comments one could require that they need to be on a new line:

```
# this ressource
c137.csv 19uheidhlkjdwhoiwuhc0uhcwljchw9ochwochw89dcgw9dcgwc
# that ressource
cronen.csv 1upodh2ioduhw9celdjhlfvhksgdwikdgcowjhcwoduchowjg8w
```
However, it's probably not really possible to use this in a backward-compatible way...

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
@mathause yeah, that should have been implemented from the start actually. But it would be nice to add them now with a notice that projects would need to require a minimum version of Pooch if they wish to use this. Pooch is a pretty light dependency and we haven't included any backwards incompatible changes since dropping 2.7.

**Comment by mathause** [comment]
This might work by replacing the following line

https://github.com/fatiando/pooch/blob/01341a9dc8de352112296131326ddaae6a7135f9/pooch/core.py#L638

with something along the line of:
```python
line = line.strip()

# skip comments
if line.startswith("#"):
    continue

elements = line.split() 

# filter out inline comments
elements = list(filter(lambda element: not element.startswith("#"), elements))
```
I assume neither filenames nor hashes nor urls should start with a `#`.

**Comment by leouieda** [comment]
> I assume neither filenames nor hashes nor urls should start with a #.

I sincerely hope no one is crazy enough to start their file names with `#` but I've been surprised before...

That seems like a good enough solution for the minimal registry file format of Pooch. Would you be able to submit a PR with that fix?
