### ISSUE TITLE
Download from Zenodo using a DOI instead of URL

### ISSUE THREAD

**Issue by bmcfee** [fatiando/pooch#177]
**Description of the desired feature**

(opening this issue per request from @leouieda )

It would be handy to have a specific downloader for data hosted on Zenodo, which could allow data to be specified in the registry by DOI rather than an absolute URL.

**Are you willing to help implement and maintain this feature?** No

But I'm willing to help test-drive it!

**Comment by leouieda** [comment]
Thanks @bmcfee :slightly_smiling_face: 

If anyone is interested in taking a shot at this, let me know. 

I'm really short on time right now but might be able to give it a go next month (or as a special treat when I finish marking).

**Comment by leouieda** [comment]
The downloader class should be based on `HTTPDownloader`. It would likely have to first make a request to the Zenodo API or something to get the file download URL and then give that URL to `HTTPDownloader`. There might be an easier way but I'm not that familiar with how DOIs work.

**Comment by leouieda** [comment]
@Xarthisius thanks for the links! Yeah, I've seen some packages out there implementing the Zenodo API for Python but I'm not sure they are still being maintained. Might be worth a shot or maybe taking over an existing one?

**Comment by leouieda** [comment]
#241 adds support for figshare DOIs and the same process could probably be adapted for Zenodo as well. It was actually not too bad and wouldn't require extensive use of their API.

**Comment by leouieda** [comment]
Actually, it was pretty easy to add Zenodo support as well and I could refactor that PR to add both without much repetition.
