### ISSUE TITLE
Add support for zip files.

### ISSUE THREAD

**Issue by MarkWieczorek** [fatiando/pooch#183]
When trying to download `.zip` file using pooch, along with `processor=Decompress()`, I received the following error:

```
Unrecognized extension '.zip'. Must be one of '['.xz', '.gz', '.bz2']'.
```

Zip files are common, so it would be great to support this format.

**Comment by luke-gregor** [comment]
Just came across this issue too. 
Zip files are actually supported. Just use the processor `pooch.Unzip`.

**Comment by leouieda** [comment]
Ah, thanks for answering @luke-gregor :slightly_smiling_face: We separated decompression from archive unpacking but maybe we shouldn't have. 

The `Unzip` processor can extract a single file from the archive or unpack the entire archive and return all of the files.

**Comment by MarkWieczorek** [comment]
Now that I know that is how it is done, that's ok. I see why zip files have to be treated specially, but one common situation is that the zip archive only contains a single file that is compressed. If you want to close this, go ahead.

**Comment by MarkWieczorek** [comment]
As an after thought, you could perhaps clarify the error message to something like "To decompress zip files, use processor=pooch.Unzip"

**Comment by leouieda** [comment]
@MarkWieczorek absolutely! See #184
