### ISSUE TITLE
Improvements to GitHub Actions workflows

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#195]
PR #194 introduces GitHub Actions as our continuous integration for most systems, replacing Azure Pipelines. We're still using TravisCI to do the deployment to PyPI and Github Pages. A few things that could be improved:

- [x] Deploy packages from the master branch to test.pypi.org. This let's us check the PyPI upload and catch problems before we try to do a release.
- [x] Deploy to PyPI on tag builds.
- [x] Deploy the documentation pages to gh-pages on master and tag builds. This will likely require an adaptation of our current scripts in [continuous-integration](https://github.com/fatiando/continuous-integration). We might be able to repurpuse an existing Action instead.
- [x] Add a job to test on Python 3.9-dev. Would need to use the system Python instead of miniconda and install packages with `pip`. 
- [ ] Use reviewdog to make comments inline from flake8 output (see [this comment](https://github.com/fatiando/pooch/pull/194#discussion_r460436581))

The PyPI deployments can be done with [pypi-publish](https://github.com/marketplace/actions/pypi-publish) (see [this comment](https://github.com/fatiando/pooch/pull/194#issuecomment-663577152) for details).

Of all of these, the first 3 are a priority since they would allow us to move away from TravisCI for good.

**Comment by hugovk** [comment]
> 1. Deploy packages from the master branch to test.pypi.org. This let's us check the PyPI upload and catch problems before we try to do a release.
> 2. Deploy to PyPI on tag builds.

Here's an example: 

* https://github.com/hugovk/tinytext/blob/master/.github/workflows/deploy.yml

**Comment by leouieda** [comment]
Deployment to PyPI was implemented in #196 and to GitHub Pages in #198.

**Comment by leouieda** [comment]
Closing this since we don't really need the reviewdog bit.
