### ISSUE TITLE
Possible legal issues with the logo

### ISSUE THREAD

**Issue by KOLANICH** [fatiando/pooch#222]
I once wanted to use a logo in colors of python in order to highlight that my project is intended to be used with python (it is essentially python bindings to some third-party code), but feeled like they can be trademarked.

I have contacted the email and asked for clarifiaction and permission. I was told that currently they don't intend to trademark python colors and that if I start using my logo, I'd "be" a my trademark (damn this legal shit, I wish there would be no trademark laws at all!). But the colors are already a de-facto trademark.

I asked if they can either give me a digitally signed text that the use of the colors in my logo is not considered trademark violation, or change their trademark policy to clarify which uses of colors are explicitly allowed. I was answered that this is the decision which is up to the board, and the board won't do that for me unless maybe for a lot of money.

IMHO this FUD situation is a bit annoying.

https://pyright.blogspot.com/2011/02/svg-xml-and-python-logo.html
https://github.com/Nuitka/Nuitka-website/issues/19
https://github.com/PyAV-Org/PyAV/issues/728
https://github.com/derb12/mcetl/issues/13
https://github.com/ReagentX/Logria-py/issues/147
https://github.com/python-trio/trio/issues/1828
https://github.com/amcc1996/symbeam/issues/7
https://github.com/cjdoris/Python.jl/issues/3
https://github.com/fatiando/pooch/issues/222
https://github.com/aiortc/aiortc/issues/442
https://github.com/MatthijsKamstra/haxepython/issues/3

**Comment by leouieda** [comment]
Thanks for opening this issue but that's likely not a problem for us. While they don't explicitly trademark the colors, there is this part of the [policy](https://www.python.org/psf/trademarks/):

> Use of derived logos for freely distributed 3rd-party modules or tools -- Allowed if for the Python programming language. Use of derived logos for commercial modules and tools requires permission from the PSF.

**Comment by KOLANICH** [comment]
I wonder if adding an address for donations will make the usage commercial...

**Comment by leouieda** [comment]
Ah, fair point. I'll keep this open then so we can keep it in mind.

**Comment by KOLANICH** [comment]
I have managed to get some kind of a cryptographic proof. The email conversation between me and PSF employee is signed by SMTP servers using DKIM. If we assumme that the servers are trusted, and sign only the emails that they have actually send, and if noone can forge a signature, we get a proof.

This was used to authenticate the leaked emails dumped to WikiLeaks, and there are some python libs for that.

So the solution is to publish the email conversation to the PSF employee (for my case I asked if he gives the consent to publish them, and he has given), and then anyone in the Net can check the signatures.

We also rely on a yet another trusted third party for backups and timestamping (instead we can rely on blockchain, but it is too costly).

1. We archive the public keys that GMail has used to sign the messages with a kind of proof that they belonged to GMail. DNS over HTTPS servers allow us to get the result of DNS lookup as a text over HTTP. And Web Archive archives the pages served over HTTP. So we just construct a lookup URI and feed it into Web Archive, and then we have a link to DNS resolution at some point in time.

2. If Google published their private DKIM keys to make the signatures repudiable (so anyone in the Net can forge them), there is a countermeasure. We hash the archive of the emails, and then feed the link to Web Archive. Then we have a proof that the archive has existed before release of the keys.
