### ISSUE TITLE
Pooch package is not setting his version properly

### ISSUE THREAD

**Issue by jujudusud** [fatiando/pooch#225]
**Description of the problem**
Version is setting to 0+untagged.3.g8f5abde instead of 1.3.0 when building the latest release 1.3.0.

a simple :
`python -c "import versioneer; print(versioneer.get_version())"`
in the source directory returns :
`0+untagged.3.g8f5abde `
Cloning the sources of the master branch returns :
`v1.3.0+1.g7424c0d`

Is it possible to look a that and update the release package ?
I need that to have a updated package in Archlinux.
Thanks.

**Comment by leouieda** [comment]
Hi @jujudusud where are you getting the source from? With versioneer, you have to either use a git clone or the archives on PyPI: https://pypi.org/project/pooch/ Download the source through http from GitHub won't work. 

Do you need the 1.3.0 release or the version on the master branch?

**Comment by jujudusud** [comment]
Hi leouieda,
The AUR (Archlinux Users Repository) is downloading the sources from GitHub. Effectivelly, It doesn't work ! :-)
I will tell the package mainteners to change to download location to pypi.org one.
I just need the latest release available here : [link to pypi latest release](https://files.pythonhosted.org/packages/87/f3/f310928da73497829de2d5412765699f96bec6f43221f2d844ac7e700ba5/pooch-1.3.0.tar.gz)
Thanks a lot for your help and for all the Pooch excellent stuff ! :-)
I will close this issue now.
