### ISSUE TITLE
Using unittest.mock.ANY as a hash raises exception

### ISSUE THREAD

**Issue by djhoese** [fatiando/pooch#226]
**Description of the problem**

I'm new to pooch so I could be doing something wrong, but when I try to use `unittest.mock.ANY` as the hash for my file I get an exception.

**Full code that generated the error**

```python
import unittest
p = pooch.create('/tmp', '/', registry={'test.tif': unittest.mock.ANY}, urls={'test.tif': "https://neo.sci.gsfc.nasa.gov/archive/blackmarble/2016/global/BlackMarble_2016_3km_geo.tif"})
p.fetch('test.tif')
```

**Full error message**

```
Downloading file 'test.tif' from 'https://neo.sci.gsfc.nasa.gov/archive/blackmarble/2016/global/BlackMarble_2016_3km_geo.tif' to '/tmp'.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-66ceaf5cbf3a> in <module>
----> 1 p.fetch('test.tif')

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/pooch/core.py in fetch(self, fname, processor, downloader)
    543                 downloader,
    544                 pooch=self,
--> 545                 retry_if_failed=self.retry_if_failed,
    546             )
    547

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/pooch/core.py in stream_download(url, fname, known_hash, downloader, pooch, retry_if_failed)
    723             with temporary_file(path=str(fname.parent)) as tmp:
    724                 downloader(url, tmp, pooch)
--> 725                 hash_matches(tmp, known_hash, strict=True, source=str(fname.name))
    726                 shutil.move(tmp, str(fname))
    727             break

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/pooch/utils.py in hash_matches(fname, known_hash, strict, source)
    376     if known_hash is None:
    377         return True
--> 378     algorithm = hash_algorithm(known_hash)
    379     new_hash = file_hash(fname, alg=algorithm)
    380     matches = new_hash.lower() == known_hash.split(":")[-1].lower()

~/miniconda3/envs/satpy_py37/lib/python3.7/site-packages/pooch/utils.py in hash_algorithm(hash_string)
    336     if hash_string is None:
    337         algorithm = default
--> 338     elif ":" not in hash_string:
    339         algorithm = default
    340     else:

TypeError: argument of type '_ANY' is not iterable
```

**System information**

* Operating system: Ubuntu/PopOS
* Python installation (Anaconda, system, ETS): Miniconda/conda-forge
* Version of Python: 3.7
* Version of this package: 1.3.0
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
affine                    2.3.0                      py_0    conda-forge
aggdraw                   1.3.11                    dev_0    <develop>
aiohttp                   3.7.3            py37h5e8e339_1    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py37h5e8e339_2    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
atk                       2.36.0               ha770c72_4    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bashlex                   0.14                     pypi_0    pypi
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
behave                    1.2.6           py37hc8dfbb8_1002    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
bokeh                     2.2.3            py37h89c1867_0    conda-forge
boolean.py                3.7                        py_0    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
boto3                     1.16.25            pyhd8ed1ab_0    conda-forge
botocore                  1.19.55            pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cachetools                4.1.1                      py_0    conda-forge
cairo                     1.16.0            h488836b_1006    conda-forge
cartopy                   0.18.0           py37h55f60b2_1    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.4           py37h11fe52a_0    conda-forge
cfgv                      3.2.0                      py_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
cftime                    1.3.0            py37h902c9e0_0    conda-forge
chardet                   3.0.4           py37he5f6b98_1008    conda-forge
charls                    2.1.0                he1b5a44_2    conda-forge
cibuildwheel              1.3.0                    pypi_0    pypi
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-default-group       1.2.1                      py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
conda                     4.9.2            py37h89c1867_0    conda-forge
conda-build               3.20.5           py37he5f6b98_0    conda-forge
conda-forge-pinning       2021.01.15.17.44.36      hd8ed1ab_0    conda-forge
conda-lock                0.7.3              pyhd8ed1ab_0    conda-forge
conda-pack                0.5.0              pyh9f0ad1d_0    conda-forge
conda-package-handling    1.7.2            py37hb5d75c8_0    conda-forge
conda-smithy              3.8.5              pyhd8ed1ab_0    conda-forge
configobj                 5.0.6                    pypi_0    pypi
coverage                  5.3              py37h8f50634_1    conda-forge
cryptography              3.3.1            py37h7f0c10b_1    conda-forge
cudatoolkit               11.1.1               h6406543_6    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py37hcd2ae1e_2    conda-forge
cytoolz                   0.11.0           py37h4abf009_1    conda-forge
dask                      2.30.0                     py_0    conda-forge
dask-core                 2.30.0                     py_0    conda-forge
dask-labextension         3.0.0                      py_0    conda-forge
datashader                0.12.0             pyhd3deb0d_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
deprecated                1.2.10             pyh9f0ad1d_0    conda-forge
distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
distributed               2.30.1           py37h89c1867_0    conda-forge
docutils                  0.16             py37h89c1867_3    conda-forge
donfig                    0.5.0+9.g1babbde           dev_0    <develop>
eccodes                   2.19.1               ha0e6eb6_0    conda-forge
editdistance              0.5.3            py37hcd2ae1e_3    conda-forge
ensureconda               1.4.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
ffmpeg                    4.3.1                hca11adc_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fiona                     1.8.17           py37ha3d844c_0    conda-forge
flake8                    3.8.4                      py_0    conda-forge
flake8-docstrings         1.5.0                      py_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      2.001                hab24e00_0    conda-forge
font-ttf-source-code-pro  2.030                hab24e00_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
gcsfs                     0.7.1                      py_0    conda-forge
gdal                      3.1.2            py37h4b180d9_0    conda-forge
gdk-pixbuf                2.42.2               h19a9c64_1    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.6.0                h05acad5_0    conda-forge
geoviews                  1.8.2                      py_0    conda-forge
geoviews-core             1.8.2                      py_0    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
git                       2.30.0          pl5320h014a29a_0    conda-forge
git-filter-repo           2.27.1                   pypi_0    pypi
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.12             pyhd8ed1ab_0    conda-forge
glib                      2.66.3               h58526e2_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
gobject-introspection     1.66.1           py37h9019ea4_3    conda-forge
google-auth               1.24.0             pyhd3deb0d_0    conda-forge
google-auth-oauthlib      0.4.2              pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.42.3               h6939c30_2    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gtk2                      2.24.32              h194ddfc_3    conda-forge
gts                       0.7.6                h1fc3fae_2    conda-forge
h5netcdf                  0.8.1                      py_0    conda-forge
h5py                      3.1.0           nompi_py37h1e651dc_100    conda-forge
harfbuzz                  2.7.2                ha5b49bf_1    conda-forge
hdf4                      4.2.13            h10796ff_1004    conda-forge
hdf5                      1.10.6          nompi_h2750804_1111    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.14.1             pyhd3deb0d_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
identify                  1.5.12             pyhd3deb0d_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py37h5f9c477_4    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imageio-ffmpeg            0.4.2                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        2.0.0                      py_1    conda-forge
importlib_metadata        2.0.0                         1    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intake                    0.6.0                      py_0    conda-forge
intake-stac               0.3.0                      py_0    conda-forge
intake-xarray             0.4.1              pyhd8ed1ab_0    conda-forge
ipdb                      0.13.4             pyhd3deb0d_0    conda-forge
ipykernel                 5.4.2            py37h888b3d9_0    conda-forge
ipython                   7.19.0           py37h888b3d9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.17.2           py37h89c1867_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter-server-proxy      1.5.3              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.0            py37h89c1867_0    conda-forge
jupyterlab                2.2.9                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kealib                    1.4.14               h0042707_0    conda-forge
kiwisolver                1.3.1            py37h2527ec5_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libaec                    1.0.4                h9c3ff4c_1    conda-forge
libarchive                3.5.1                h899b81a_0    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libclang                  10.0.1          default_hde54327_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdap4                   3.20.6               h1d1bd15_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgdal                   3.1.2                h6687615_0    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.3               hbe7bbb4_0    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h74f7ee3_1012    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
liblief                   0.10.1               he1b5a44_2    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnetcdf                 4.7.4           nompi_hefab0ff_106    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libprotobuf               3.14.0               h780b84a_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             4.3.0a            h2482549_1038    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   0.4.2                    pypi_0    pypi
libtool                   2.4.6             h58526e2_1007    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.1.0                h76fa15c_4    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
license-expression        1.2                        py_0    conda-forge
llvmlite                  0.34.0           py37h5202443_2    conda-forge
locket                    0.2.0                      py_2    conda-forge
loghub                    0.4.0                    pypi_0    pypi
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py37h5e8e339_3    conda-forge
matplotlib                3.3.3            py37h89c1867_0    conda-forge
matplotlib-base           3.3.3            py37h0c9df89_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h5e8e339_1003    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
msrest                    0.6.19             pyh9f0ad1d_0    conda-forge
multidict                 5.1.0            py37h5e8e339_1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
mysql-common              8.0.21                        2    conda-forge
mysql-libs                8.0.21               hf3661c5_2    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37h89c1867_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.4           nompi_py37hcbfd489_103    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.5                        py_0    conda-forge
nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
notebook                  6.2.0            py37h89c1867_0    conda-forge
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.60                 hb5efdd6_0    conda-forge
numba                     0.51.2           py37h9fdb41a_0    conda-forge
numcodecs                 0.7.2            py37hcd2ae1e_1    conda-forge
numpy                     1.19.4           py37h7e9df27_1    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.3.1                hf7af979_3    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
owslib                    0.21.0             pyhd8ed1ab_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandas                    1.2.0            py37hdc94413_1    conda-forge
pandoc                    2.11.3.2             h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.10.2             pyhd8ed1ab_0    conda-forge
pango                     1.42.4               h69149e4_5    conda-forge
param                     1.10.1             pyhd3deb0d_0    conda-forge
parse                     1.19.0             pyh44b312d_0    conda-forge
parse_type                0.5.2            py37h89c1867_3    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.32.0               h36c2ea0_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py37he6b4880_1    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.6.1              pyh9f0ad1d_0    conda-forge
pluggy                    0.13.1           py37h89c1867_4    conda-forge
pooch                     1.3.0              pyhd8ed1ab_0    conda-forge
poppler                   0.89.0               h4190859_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 hc2f5b80_3    conda-forge
pre-commit                2.9.2            py37h89c1867_0    conda-forge
proj                      7.0.0                h966b41f_5    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
prompt_toolkit            3.0.10               hd8ed1ab_0    conda-forge
protobuf                  3.14.0           py37hcd2ae1e_1    conda-forge
psutil                    5.8.0            py37h5e8e339_1    conda-forge
psycopg2                  2.8.6            py37hb09aad4_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
py-lief                   0.10.1           py37hb892b2f_2    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pybind11                  2.6.1            py37h2527ec5_3    conda-forge
pybind11-global           2.6.1            py37h2527ec5_3    conda-forge
pycoast                   1.3.2+0.geb35e25.dirty           dev_0    <develop>
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py37h5e8e339_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py37hb5d75c8_1005    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydecorate                0.2.2.dev14+g2685838.d20200406           dev_0    <develop>
pydocstyle                5.1.1                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygithub                  1.53                       py_0    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pygrib                    2.0.6            py37h780c4fe_0    conda-forge
pyhdf                     0.10.2           py37hb36aea3_2    conda-forge
pyjwt                     2.0.0              pyhd8ed1ab_0    conda-forge
pykdtree                  1.3.4            py37ha21ca33_0    conda-forge
pyninjotiff               0.3.0                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyorbital                 1.6.0              pyh9f0ad1d_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.0            py37h34dd122_1    conda-forge
pyqt                      5.12.3           py37h89c1867_7    conda-forge
pyqt-impl                 5.12.3           py37he336c9b_7    conda-forge
pyqt5-sip                 4.19.18          py37hcd2ae1e_7    conda-forge
pyqtchart                 5.12             py37he336c9b_7    conda-forge
pyqtwebengine             5.12.1           py37he336c9b_7    conda-forge
pyresample                1.17.0+26.g6f47381.dirty           dev_0    <develop>
pyrsistent                0.17.3           py37h5e8e339_2    conda-forge
pyshp                     2.1.2              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py37h89c1867_3    conda-forge
pyspectral                0.9.1+3.g6f7f569.dirty           dev_0    <develop>
pytest                    6.1.2            py37h89c1867_0    conda-forge
pytest-cov                2.10.1             pyh9f0ad1d_0    conda-forge
python                    3.7.8           h8bdb77d_2_cpython    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
python-eccodes            2020.10.1        py37ha21ca33_0    conda-forge
python-geotiepoints       1.2.0            py37h03ebfcd_0    conda-forge
python-graphviz           0.15               pyhd3deb0d_0    conda-forge
python-libarchive-c       2.9              py37h89c1867_2    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
pywavelets                1.1.1            py37h902c9e0_3    conda-forge
pyyaml                    5.3.1            py37h5e8e339_2    conda-forge
pyzmq                     21.0.0           py37h499b945_0    conda-forge
qt                        5.12.9               h1f2b2cb_0    conda-forge
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rasterio                  1.1.6            py37ha3d844c_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rioxarray                 0.1.2.dev0                dev_0    <develop>
ripgrep                   12.1.1               h516909a_1    conda-forge
rsa                       4.7                pyhd3deb0d_0    conda-forge
rtree                     0.9.7            py37h0b55af0_1    conda-forge
ruamel.yaml               0.16.12          py37h5e8e339_2    conda-forge
ruamel.yaml.clib          0.2.2            py37h5e8e339_2    conda-forge
ruamel_yaml               0.15.80         py37h5e8e339_1003    conda-forge
s3fs                      0.4.2                      py_0    conda-forge
s3transfer                0.3.4              pyhd8ed1ab_0    conda-forge
sat-stac                  0.4.0              pyh9f0ad1d_0    conda-forge
satpy                     0.25.2.dev26+g2df64af2.d20210123           dev_0    <develop>
scikit-image              0.17.2           py37h10a2094_4    conda-forge
scipy                     1.5.3            py37h14a347d_0    conda-forge
scrypt                    0.8.17           py37h7f0c10b_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
shapely                   1.7.1            py37hedb1597_1    conda-forge
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
siphon                    0.8.0           py37hc8dfbb8_1004    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
snakeviz                  2.1.0              pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    3.3.1              pyhd8ed1ab_0    conda-forge
sphinx_rtd_theme          0.5.0              pyh9f0ad1d_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tbb                       2020.2               h4bd325d_3    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.2            py37h89c1867_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tifffile                  2020.11.26         pyhd8ed1ab_0    conda-forge
tiledb                    2.0.8                h3effe38_1    conda-forge
tiledb-py                 0.6.6            py37haae2426_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py37h5e8e339_1    conda-forge
tqdm                      4.53.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
trollimage                1.14.0                   pypi_0    pypi
trollsift                 0.3.2                     dev_0    <develop>
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzcode                    2020f                h7f98852_0    conda-forge
udunits                   2.2.17                        6    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
virtualenv                20.3.1           py37h89c1867_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py37h89c1867_4    conda-forge
wrapt                     1.12.1           py37h5e8e339_3    conda-forge
x264                      1!161.3030           h7f98852_0    conda-forge
xarray                    0.16.1                     py_0    conda-forge
xerces-c                  3.2.3                hfe33f54_1    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.6.3            py37h5e8e339_1    conda-forge
zarr                      2.5.0                      py_0    conda-forge
zeromq                    4.3.3                h58526e2_3    conda-forge
zfp                       0.5.5                h9c3ff4c_4    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                hdf46e1d_0    conda-forge

</pre>
</details>

**Comment by leouieda** [comment]
@djhoese thanks for reporting! That is actually a bug and something that should have been caught by a test (turns out we didn't have any for that behavior). 

It's actually much easier to do now by passing `None` as the hash instead of `ANY`. We should update that in the docs so I opened #227 to see if there are any takers 🙂 

This should still be fixed to support the old behavior and we should have a test for this to make sure it doesn't regress again.

**Comment by djhoese** [comment]
Ah great. `None` is so much easier (and logical) anyway.

**Comment by leouieda** [comment]
Closing this as it got fixed in the latest docs refactor.
