### ISSUE TITLE
Any chance of a new release?

### ISSUE THREAD

**Issue by hmaarrfk** [fatiando/pooch#245]
Not sure if it is easy for you to cut a release, but one would be appreciated with the recent
https://github.com/fatiando/pooch/pull/244

merge request.

**Comment by santisoler** [comment]
Hi @hmaarrfk !

We have a sleek workflow for making releases, so if nothing unexpected goes wrong we can release a new version with a little manual work. @leouieda is not currently available, would you mind waiting until next week for the next release or this is something you need ASAP?

**Comment by hmaarrfk** [comment]
definitely can wait! thansk!

**Comment by santisoler** [comment]
Great! I'll open the Release Checklist Issue so I can start tackling the tasks for the release, so next week we only need to make it happen.

**Comment by santisoler** [comment]
Done: #246

**Comment by leouieda** [comment]
@hmaarrfk done! The PyPI package is already live and conda-forge should be coming soon (just waiting on the bot).
