### ISSUE TITLE
Follow FreeDesktop directory specifications

### ISSUE THREAD

**Issue by remram44** [fatiando/pooch#26]
Using `~/.cache` is not [what the standard says](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

https://github.com/fatiando/pooch/blob/9a1a5f92a1b1ffde29136468605eb9d7c14795de/pooch/utils.py#L49-L50

**Comment by remram44** [comment]
That all I remembered, and the part you quoted seems to indicate that's all there is 😃

**Comment by leouieda** [comment]
Hi @remram44 thanks for the feedback! How important is it to follow the spec to the letter? If it is, that's a relatively easy fix. 

@dopplershift and @jrleeman are the ones using the `os_cache` function. What do you think?

**Comment by remram44** [comment]
I think if that variable is set, it is set on purpose, and it wouldn't be good to have Pooch be the only app writing to the wrong path. The freedesktop specifications are widely accepted standards, and when they are so simple I don't see a reason to transgress.

**Comment by leouieda** [comment]
OK, that's a good argument. We could add a check for that variable in `os_cache` and fallback to the current dirs if it's not set. 

@dopplershift and @jrleeman do you think think would break MetPy somehow? If it's included, MetPy would only get it with a new release so the data files would be re-downloaded anyway. So I'm guessing it's not that bad.

**Comment by leouieda** [comment]
Hi @dopplershift and @jrleeman, any updates on this? We could add this feature but not make it the default behavior for now. For example, by adding a `check_environment=False` option to `os_cache` in case library developers what to follow the standard.

**Comment by dopplershift** [comment]
It’s fine to me if someone wants to add it.

**Comment by leouieda** [comment]
:+1: 

Created #43 with the feature request in case any good soul wants to contribute.
