### ISSUE TITLE
Feature suggestion: ability to set progress bar kwarg from `fetch` or `retrieve`

### ISSUE THREAD

**Issue by GenevieveBuckley** [fatiando/pooch#273]
**Description of the desired feature:**
I think it would be useful to make the [progress bar](https://github.com/fatiando/pooch/issues/91) keyword arguments accessible from `fetch()` and/or `retrieve()`. This would allow users who don't want to do a lot of setup or configuration, to also get the benefit of progress bars (plus all the same benefits of having the right downloader chosen automatically, etc.).

It's a feature I'd like to have, so I'd like to know if there is general enthusiasm for it.

**Are you willing to help implement and maintain this feature?** 
Yes. I think it would be pretty straightforward to pass an extra kwarg through to the right functions, I can make a pull request for it.

**Comment by leouieda** [comment]
👋🏽 Hi @GenevieveBuckley thanks for submitting this feature request! I agree that's pretty inconvenient to have to use `pooch.HTTPDownloader` just to get a progress bar going. It just never crossed the threshold of "I want this enough to write tests for it" for me 🙂 

Happy to get a PR for this if you're willing to implement it. As you've identified, it would be mostly adding the `progressbar=False` argument to the end of `Pooch.fetch` and `retrieve` and passing it to the downloader if one is being created. Let me know if you need any help or guidance on this. Feel free to open the PR early on in draft mode so we know you're working on this and can help if anything comes up.
