### ISSUE TITLE
Add support for DOI resolution for DataVerse repositories

### ISSUE THREAD

**Issue by dokempf** [fatiando/pooch#317]
**Description of the desired feature:**

I would like to add DOI handling support for data repositories based on [DataVerse](https://github.com/IQSS/dataverse). My main motivation is that my institution offers a data archiving service based on DataVerse. I have done a previous [first attempt](https://github.com/ssciwr/dataverse_pooch) which was based on generating registry and urls dictionaries in a wrapper around `pooch.create`. I have come to realize however that it would be a better fit to include this into `pooch` itself alongside the other DOI resolvers (plus I read that you are open to such contributions).

There is one technical difference between a DataVerse DOI converter compared to the existing ones: It cannot decide based on the URL whether it is a DataVerse repository, as institutions will typically run their own DataVerse instances (e.g. [this at Heidelberg University](https://heidata.uni-heidelberg.de/)). To account for this difference I think a refactoring of the existing DOI converter dispatch is required. I propose the following:

*Current implementation*: Converters are stored as a [mapping of base URL to a function](https://github.com/fatiando/pooch/blob/main/pooch/downloaders.py#L558:L561) -> the base URL is determined -> the correct function is called. Converter functions return a URL.

*Proposed implementation*: Converters are stored as a list -> Converters are called one after another until one of them returned a URL, they return `None` otherwise. If no converter works, an error is thrown (similar to what is currently done). This can be seen as an implementation of the [Chain of Responsibility Design Pattern](https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern).

**Are you willing to help implement and maintain this feature?** 

I will be able to contribute the implementation of this feature. Given that I have a natural interest in the feature for supporting researchers at my institution, I will also be around for helping with maintenance.

**Comment by leouieda** [comment]
Sounds good to me @dokempf. It would be great to support more services and the implementation you laid out makes perfect sense.
