### ISSUE TITLE
Automatically add a trailing "/" to base_url in pooch.create

### ISSUE THREAD

**Issue by dokempf** [fatiando/pooch#324]
**Description of the problem:**

In order to define a `Pooch` with a DOI, the DOI needs to end on a `/`. However, that character is not part of the DOI (e.g. https://dx.doi.org/ does not understand the DOI with `/`) and should not be needed here. The root of the problem is very likely a too similar handling of URLs and DOIs.

**Full code that generated the error**

Using the example from [the official docs](https://www.fatiando.org/pooch/latest/protocols.html#digital-object-identifiers-dois) and stripping the trailing `/` from `base_url`:
```python
POOCH = pooch.create(
    path=pooch.os_cache("plumbus"),
    # Use the figshare DOI
    base_url="doi:10.6084/m9.figshare.14763051.v1",
    registry={
        "tiny-data.txt": "md5:70e2afd3fd7e336ae478b1e740a5f08e",
        "store.zip": "md5:7008231125631739b64720d1526619ae",
    },
)

def fetch_tiny_data():
    """
    Load the tiny data as a numpy array.
    """
    fname = POOCH.fetch("tiny-data.txt")
    data = numpy.loadtxt(fname)
    return data
```

**Full error message**

```
ValueError: Archive with doi:10.6084/m9.figshare.14763051.v1tiny-data.txt not found (see https://doi.org/10.6084/m9.figshare.14763051.v1tiny-data.txt). Is the DOI correct?
```

**Comment by leouieda** [comment]
Good catch! Even for normal URLs that requirement is a bit silly. The downstream code for joining and parsing URLs and DOIs assumes that there is trailing `/` in the URL. So a solution to this would be to add a bit of code to `pooch.create` that makes sure there is one. That would solve this for DOIs (which really does look strange) and make the setting more flexible for other URLs.

**Comment by gabrielfu** [comment]
hi @leouieda @dokempf , this project seems interesting to me. As this issue has not been updated for months, can I try my take on this?

As this line is where the issue occurs, I suggest we do `self.base_url.rstrip("/") + "/" + fname` instead and make it more universal. 
https://github.com/fatiando/pooch/blob/d579cf6b0ae740e059bf52184982ec419d7c361a/pooch/core.py#L620

Proposed change:
https://github.com/fatiando/pooch/compare/main...gabrielfu:pooch:issue/310

**Comment by santisoler** [comment]
Hi @gabrielfu! You are more than welcome to tackle this issue! Would you like to open a Pull Request for it?

I would suggest to apply the change to the `pooch.create` function instead of the `get_url` function. The `get_url` method should be simple enough to check if the file exists in the registry and provide the url. The issue described here is mostly about interface, so it would be better to solve it at the public function that implements that interface: `pooch.create`.

Moreover, the docstring for `pooch.create` should also be update accordingly: we won't need users to add the trailing slash anymore.

**Comment by gabrielfu** [comment]
> Hi @gabrielfu! You are more than welcome to tackle this issue! Would you like to open a Pull Request for it?
> 
> I would suggest to apply the change to the `pooch.create` function instead of the `get_url` function. The `get_url` method should be simple enough to check if the file exists in the registry and provide the url. The issue described here is mostly about interface, so it would be better to solve it at the public function that implements that interface: `pooch.create`.
> 
> Moreover, the docstring for `pooch.create` should also be update accordingly: we won't need users to add the trailing slash anymore.

sure, make sense to me :) I will create a PR
