### ISSUE TITLE
HTTP Error during pooch.retrieve()

### ISSUE THREAD

**Issue by mdtanker** [fatiando/pooch#326]
**Description of the problem:**

I'm trying to download a zipped folder with supplementary info from a journal article. Here's the [link](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2018GC008111) to the article, and the download link to the supplement is at the bottom of that page.

When I call `pooch.retrieve()` on that download link, I'm receiving an HTTPError: 503 Server Error. I've tried this a few different times today, but I'll try again tomorrow incase it was a temporary issue.

**Full code that generated the error**

```python
path = pooch.retrieve(
    url="https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1029%2F2018GC008111&file=ggge21848-sup-0001-2018GC008111-SI.docx",
    known_hash=None,
    progressbar=True,
    processor=pooch.Unzip(),
)
```

**Full error message**

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In [80], line 1
----> 1 path = pooch.retrieve(
      2     url="https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1029%2F2018GC008111&file=ggge21848-sup-0001-2018GC008111-SI.docx",
      3     known_hash=None,
      4     progressbar=True,
      5     processor=pooch.Unzip(),
      6 )
      8 path

File c:\Users\matthewt\AppData\Local\miniforge3\envs\antarctic_plots_dev\lib\site-packages\pooch\core.py:240, in retrieve(url, known_hash, fname, path, processor, downloader, progressbar)
    237 if downloader is None:
    238     downloader = choose_downloader(url, progressbar=progressbar)
--> 240 stream_download(url, full_path, known_hash, downloader, pooch=None)
    242 if known_hash is None:
    243     get_logger().info(
    244         "SHA256 hash of downloaded file: %s\n"
    245         "Use this value as the 'known_hash' argument of 'pooch.retrieve'"
   (...)
    248         file_hash(str(full_path)),
    249     )

File c:\Users\matthewt\AppData\Local\miniforge3\envs\antarctic_plots_dev\lib\site-packages\pooch\core.py:772, in stream_download(url, fname, known_hash, downloader, pooch, retry_if_failed)
    768 try:
    769     # Stream the file to a temporary so that we can safely check its
    770     # hash before overwriting the original.
    771     with temporary_file(path=str(fname.parent)) as tmp:
--> 772         downloader(url, tmp, pooch)
    773         hash_matches(tmp, known_hash, strict=True, source=str(fname.name))
    774         shutil.move(tmp, str(fname))

File c:\Users\matthewt\AppData\Local\miniforge3\envs\antarctic_plots_dev\lib\site-packages\pooch\downloaders.py:190, in HTTPDownloader.__call__(self, url, output_file, pooch)
    188 try:
    189     response = requests.get(url, **kwargs)
--> 190     response.raise_for_status()
    191     content = response.iter_content(chunk_size=self.chunk_size)
    192     total = int(response.headers.get("content-length", 0))

File c:\Users\matthewt\AppData\Local\miniforge3\envs\antarctic_plots_dev\lib\site-packages\requests\models.py:1021, in Response.raise_for_status(self)
   1016     http_error_msg = (
   1017         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1018     )
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1029%2F2018GC008111&file=ggge21848-sup-0001-2018GC008111-SI.docx
```

**System information**

* Operating system:
* Python installation (Anaconda, system, ETS):
* Version of Python:
* Version of this package:
* If using conda, paste the output of `conda list` below:

<details>
<summary>Output of conda list</summary>
<pre>

# packages in environment at C:\Users\matthewt\AppData\Local\miniforge3\envs\antarctic_plots_dev:
#
# Name                    Version                   Build  Channel
affine                    2.3.1                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
antarctic-plots           0.0.4.1                  pypi_0    pypi
anyio                     3.6.1              pyhd8ed1ab_1    conda-forge
aom                       3.5.0                h63175ca_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb82d6ee_2    conda-forge
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0                   pypi_0    pypi
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
black                     22.8.0                   pypi_0    pypi
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h74325e0_3    conda-forge
boost-cpp                 1.78.0               h9f4b32c_1    conda-forge
bqplot                    0.12.36            pyhd8ed1ab_0    conda-forge
branca                    0.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.24            h5b45459_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h0878f49_0    conda-forge
cfgrib                    0.9.10.1                 pypi_0    pypi
cfitsio                   4.1.0                h5a969a9_0    conda-forge
cftime                    1.6.2            py39hc266a54_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39hcbf5309_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.2.0                    pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
contourpy                 1.0.5            py39h1f6ef14_0    conda-forge
cryptography              37.0.4           py39h7bc7c5c_0    conda-forge
curl                      7.83.1               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dask                      2022.9.1                 pypi_0    pypi
debugpy                   1.6.3            py39h415ef7b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
double-conversion         3.2.0                h63175ca_1    conda-forge
eccodes                   1.5.0                    pypi_0    pypi
eigen                     3.4.0                h2d74725_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 1.0.0                    pypi_0    pypi
expat                     2.4.8                h39d44d4_0    conda-forge
fasteners                 0.18                     pypi_0    pypi
ffmpeg                    4.4.2           gpl_h952562b_108    conda-forge
fftw                      3.3.10          nompi_h38027f0_105    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
findlibs                  0.0.2                    pypi_0    pypi
fiona                     1.8.21           py39h0a5cb73_2    conda-forge
flake8                    4.0.1                    pypi_0    pypi
flake8-pyproject          0.9.1                    pypi_0    pypi
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.2           py39ha55989b_0    conda-forge
freetype                  2.12.1               h546665d_0    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2022.8.2                 pypi_0    pypi
gdal                      3.5.2            py39h34c8707_1    conda-forge
gdown                     4.5.1              pyhd8ed1ab_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.11.0             pyhd8ed1ab_0    conda-forge
geopandas-base            0.11.0             pyha770c72_0    conda-forge
geos                      3.11.0               h39d44d4_0    conda-forge
geotiff                   1.7.1                h714bc5f_3    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
ghostscript               9.54.0               h0e60522_2    conda-forge
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.27                   pypi_0    pypi
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
gmt                       6.4.0                hace14ca_2    conda-forge
greenlet                  1.1.3                    pypi_0    pypi
gst-plugins-base          1.20.3               h001b923_2    conda-forge
gstreamer                 1.20.3               h6b5321d_2    conda-forge
h5netcdf                  1.0.2                    pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
hdf4                      4.2.15               h0e5069d_4    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imageio                   2.22.0             pyhfa7a67d_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipyevents                 2.0.1              pyhd8ed1ab_0    conda-forge
ipyfilechooser            0.6.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.3                   pypi_0    pypi
ipyleaflet                0.17.1             pyhd8ed1ab_0    conda-forge
ipysheet                  0.5.0              pyhd8ed1ab_0    conda-forge
ipython                   8.5.0              pyh08f2357_1    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipytree                   0.2.2              pyhd8ed1ab_0    conda-forge
ipywidgets                7.7.2              pyhd8ed1ab_0    conda-forge
isort                     5.10.1                   pypi_0    pypi
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsoncpp                   1.9.5                h2d74725_1    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
jupyter-book              0.13.1                   pypi_0    pypi
jupyter-cache             0.4.3                    pypi_0    pypi
jupyter-server            1.18.1                   pypi_0    pypi
jupyter-server-mathjax    0.2.6                    pypi_0    pypi
jupyter-sphinx            0.3.2                    pypi_0    pypi
jupyter_client            7.3.5              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39hcbf5309_0    conda-forge
jupyter_server            1.19.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.8              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.2             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
kealib                    1.4.15               hdf81f3a_1    conda-forge
kiwisolver                1.4.4            py39h2e07f2f_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
latexcodec                2.0.1                    pypi_0    pypi
lcms2                     2.12                 h2a16943_0    conda-forge
leafmap                   0.10.5             pyhd8ed1ab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.5.2                hc386656_1    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h85765be_104    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.38               h19919ed_0    conda-forge
libpq                     14.5                 hfcc5ef8_0    conda-forge
librttopo                 1.1.0               h2842628_11    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               ha17912d_18    conda-forge
libsqlite                 3.39.3               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtheora                 1.1.1             h8d14728_1005    conda-forge
libtiff                   4.4.0                h8e97e67_4    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hf5bbc77_4    conda-forge
libzip                    1.9.2                hfed4ece_1    conda-forge
libzlib                   1.2.12               hcfcfb64_3    conda-forge
linkify-it-py             1.0.3                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
loguru                    0.6.0            py39hcbf5309_1    conda-forge
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markdown-it-py            1.1.0                    pypi_0    pypi
markupsafe                2.1.1            py39hb82d6ee_1    conda-forge
matplotlib-base           3.6.0            py39haf65ace_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
mdit-py-plugins           0.2.8                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy-extensions           0.4.3                    pypi_0    pypi
myst-nb                   0.13.2                   pypi_0    pypi
myst-parser               0.15.2                   pypi_0    pypi
nbclassic                 0.4.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.13                   pypi_0    pypi
nbconvert                 6.5.3                    pypi_0    pypi
nbconvert-core            7.1.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.1.0              pyhd8ed1ab_0    conda-forge
nbdime                    3.1.1                    pypi_0    pypi
nbformat                  5.5.0                    pypi_0    pypi
nbsphinx                  0.8.9                    pypi_0    pypi
nest-asyncio              1.5.5                    pypi_0    pypi
netcdf4                   1.6.1           nompi_py39h34fa13a_100    conda-forge
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
numcodecs                 0.10.2                   pypi_0    pypi
numpy                     1.23.3           py39h9061af7_0    conda-forge
openh264                  2.3.1                h63175ca_1    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openpyxl                  3.0.10           py39ha55989b_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.5.0            py39h2ba5b7c_0    conda-forge
pandoc                    2.19.2               h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0                    pypi_0    pypi
pathspec                  0.10.1                   pypi_0    pypi
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py39hcef8f5f_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
pooch                     1.6.0                    pypi_0    pypi
poppler                   22.04.0              hb57f792_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.5                 h1c22c4f_0    conda-forge
proj                      9.0.1                h1cfcee9_1    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
pscript                   0.7.7              pyhd8ed1ab_0    conda-forge
psutil                    5.9.2            py39ha55989b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pugixml                   1.11.4               h0e60522_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0                   pypi_0    pypi
pybtex                    0.24.0                   pypi_0    pypi
pybtex-docutils           1.0.2                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycrs                     1.0.2                      py_0    conda-forge
pydap                     3.2.2                    pypi_0    pypi
pydata-sphinx-theme       0.8.1                    pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pygmt                     0.7.0              pyhd8ed1ab_0    conda-forge
pyogrio                   0.4.1                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.4.0            py39h2de216b_0    conda-forge
pyrsistent                0.18.1           py39hb82d6ee_1    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pystac                    1.6.1              pyhd8ed1ab_1    conda-forge
pystac-client             0.5.1              pyhd8ed1ab_0    conda-forge
pytest                    7.1.3                    pypi_0    pypi
python                    3.9.13          h9a09f29_0_cpython    conda-forge
python-box                6.0.2            py39ha55989b_3    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyvista                   0.36.1             pyhd8ed1ab_0    conda-forge
pyvista-xarray            0.1.1              pyhd8ed1ab_0    conda-forge
pywin32                   304                      pypi_0    pypi
pywinpty                  2.0.8            py39h99910a6_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.0                   pypi_0    pypi
qt-main                   5.15.6               hf0cf448_0    conda-forge
rasterio                  1.3.2                    pypi_0    pypi
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
rioxarray                 0.12.1                   pypi_0    pypi
rtree                     1.0.0            py39h09fdee3_1    conda-forge
ruamel.yaml               0.17.21          py39hb82d6ee_1    conda-forge
ruamel.yaml.clib          0.2.6            py39hb82d6ee_1    conda-forge
scikit-learn              1.1.2            py39hfd4428b_0    conda-forge
scipy                     1.9.1            py39h316f440_0    conda-forge
scooby                    0.6.0              pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
setuptools-scm            7.0.5                    pypi_0    pypi
shapely                   1.8.4            py39he0923fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0                    pypi_0    pypi
snappy                    1.1.9                h82413e6_1    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
snuggs                    1.4.7                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0                    pypi_0    pypi
sphinx-book-theme         0.3.3                    pypi_0    pypi
sphinx-comments           0.0.3                    pypi_0    pypi
sphinx-copybutton         0.5.0                    pypi_0    pypi
sphinx-design             0.1.0                    pypi_0    pypi
sphinx-external-toc       0.2.4                    pypi_0    pypi
sphinx-gallery            0.11.1                   pypi_0    pypi
sphinx-jupyterbook-latex  0.4.6                    pypi_0    pypi
sphinx-multitoc-numbering 0.1.3                    pypi_0    pypi
sphinx-thebe              0.1.2                    pypi_0    pypi
sphinx-togglebutton       0.3.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-bibtex      2.5.0                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.41                   pypi_0    pypi
sqlite                    3.39.3               hcfcfb64_0    conda-forge
stack-data                0.5.0                    pypi_0    pypi
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
svt-av1                   1.2.1                h0e60522_0    conda-forge
tbb                       2021.5.0             h91493d7_2    conda-forge
tbb-devel                 2021.5.0             h91493d7_2    conda-forge
terminado                 0.15.0                   pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.11.2               h5689973_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tokenize-rt               4.2.1                    pypi_0    pypi
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.2              py39hb82d6ee_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
uc-micro-py               1.0.1                    pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
utfcpp                    3.2.1                h57928b3_0    conda-forge
vc                        14.2                 hb210afc_7    conda-forge
verde                     1.7.0                    pypi_0    pypi
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    pypi_0    pypi
webob                     1.8.7                    pypi_0    pypi
websocket-client          1.4.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whitebox                  2.1.4              pyhd8ed1ab_0    conda-forge
whiteboxgui               0.7.0              pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
win32_setctime            1.1.0              pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
winpty                    0.4.3                         4    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.3                h0e60522_5    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xyzservices               2022.9.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zarr                      2.12.0                   pypi_0    pypi
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               hcfcfb64_3    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge

</pre>
</details>

**Comment by leouieda** [comment]
Hi @mdtanker have you tried downloading with curl or wget on the command line? My suspicion is that Wiley are blocking the download from a non-browser agent because they are horrible. 

A way around this (if it is the case) is to set the user agent to the name of a browser when making the GET request to their website. See this post https://www.shellhacks.com/python-requests-user-agent-web-scraping/ You can pass the required `header` argument to `requests.get` by setting it as a keyword argument in a `HTTPDownloader`:

```python
headers = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0'
}
path = pooch.retrieve(
    url="https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1029%2F2018GC008111&file=ggge21848-sup-0001-2018GC008111-SI.docx",
    known_hash=None,
    progressbar=True,
    processor=pooch.Unzip(),
    downloader=pooch.HTTPDownloader(headers=headers),
)
```

**Comment by leouieda** [comment]
To be clear, this isn't a problem with Pooch but the website not allowing automated downloads. This is why I'm firmly against uploading things as supplements like this, even if you publish open access. Put things on figshare or zenodo instead.

**Comment by mdtanker** [comment]
Wow that is annoying of them. Thanks for the explanation. I've tried your above code, but still get the same 503 Server Error. 

I tried with curl and wget without any success. I also tied with just the requests package (and lots of variations of the user-agent), as below, but still getting the same error:
```python
import requests

url="https://agupubs.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1029%2F2018GC008111&file=GGGE_21848_DataSetsS1-S6.zip"
headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36',
    }
page = requests.get(url, headers = headers)
print(page)
```

Unless you have any other ideas, I might just abandon trying to download this. Thanks!
