### ISSUE TITLE
Download from URL with expired SSL certificate

### ISSUE THREAD

**Issue by tomasstolker** [fatiando/pooch#360]
Thanks a lot for providing this really helpful tool!

I am trying to download a file from an URL that has an expired SSL certificate. I know that the URL is safe to use so I want to try to circumvent the error. Any suggestion on how to do that with `pooch`?

The error that I get is the following, which is caused by `urllib3` / `ssl`:

_ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired_

**Comment by dokempf** [comment]
Hey @tomasstolker! `pooch` is using the `requests` library under the hood which allows you to [disable SSL checking](https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests). The way to pass such an option to `pooch` would be to manually instantiate the `HTTPDownloader`:

```python
import pooch

downloader = pooch.HTTPDownloader(verify=False)
filename = pooch.retrieve(URL, known_hash=HASH, downloader=downloader)
```

Note that I tested the above snippet, but only with a server that also has a certificate.

**Comment by tomasstolker** [comment]
Thanks a lot for your quick reply @dokempf! That works perfectly!

**Comment by santisoler** [comment]
Thanks @tomasstolker for opening this issue, and thanks @dokempf for the reply!

I think this issue has been resolves, so I'm closing it.

I still want to mention (specially for future readers) that disabling SSL verification **is not a secure practice** and **it could potentially lead to getting malware in our systems**.

🚨🚨🚨 
So, **BE EXTREMELY CAUTIOUS** when using `verify=False`, and I **highly discourage distributing code** with that option.
🚨🚨🚨
