### ISSUE TITLE
If Unzip/Untar fails because of a non-existent member, calling without members won't work

### ISSUE THREAD

**Issue by jni** [fatiando/pooch#364]
**Description of the problem:**

Unfortunately #316 still doesn't quite fix the problem of dealing with members in archives. It creates a race condition where calling with members before calling without them will cause the `members=None` call to return an incomplete archive — and in the case of a failed earlier call, it will be empty.

The issue is that if members is None, we still only check for the existence of the unzip directory:

https://github.com/fatiando/pooch/blob/9c57dd38c8fa8d20e2c4f2cfa41ac3d33be78138/pooch/processors.py#L84-L86

But the directory does not necessarily contain every member we need.

**Full code that generated the error**

(With thanks to @dokempf for the example 😃)

```python
import pooch

P = pooch.create(
    path=pooch.os_cache("test"),
    base_url="https://github.com/ssciwr/afwizard-test-data/releases/download/2022-06-09/",
    registry={
        "data.tar.gz": "sha256:fae90a3cf758e2346b81fa0e3b005f2914d059ca182202a1de8f627b1ec0c160"
    }
)
try:
    files1 = P.fetch("data.tar.gz", processor=pooch.Untar(members=["i don't exist"]))
except:
    pass
files2 = P.fetch("data.tar.gz", processor=pooch.Untar())

assert len(files2) > 0
```

The assertion fails, and will fail forever now, even if we remove the faulty fetch! (State is hard. 😅)

```
Downloading file 'data.tar.gz' from 'https://github.com/ssciwr/afwizard-test-data/releases/download/2022-06-09/data.tar.gz' to '/Users/jni/Library/Caches/test'.
Extracting 'i don't exist' from '/Users/jni/Library/Caches/test/data.tar.gz' to '/Users/jni/Library/Caches/test/data.tar.gz.untar'
Traceback (most recent call last):
  File "/Users/jni/projects/play/pooch-test.py", line 16, in <module>
    assert len(files2) > 0
AssertionError
```

**Suggested fix**

At the start of `__call__`, we should check if `members` is None, and if so, set `members` to the full list of files from the archive. Then I think everything else should work nicely. 😊 And it might simplify some of the later conditionals.

**System information**

* Operating system: macOS 13.4
* Python installation (Anaconda, system, ETS): conda
* Version of Python: 3.10
* Version of this package: 1.7.0
* If using conda, paste the output of `conda list` below: (nah you don't want this 😂)

**Comment by jni** [comment]
(And actually I just noticed that my try/except is pointless because the incorrect member call fails silently. Should I open another issue for that? 😅)

**Comment by leouieda** [comment]
@jni good catch! And indeed, state is hard... 

> Should I open another issue for that? 😅

Hopefully fixing this will solve both problems 🤞🏾
