### ISSUE TITLE
Feature: allow null hash in registry files

### ISSUE THREAD

**Issue by tlambert03** [fatiando/pooch#366]
**Description of the desired feature:**
[registry files](https://www.fatiando.org/pooch/latest/registry-files.html) are a nice way to load a large registry without a dict, and they also support custom urls for each file.  However, if one doesn't know the hash value up front and wants to [bypass the hash check](https://www.fatiando.org/pooch/latest/hashes.html#bypassing-the-hash-check), then you need to either use a dict instead of a registry file, manually or clear all the values after calling `load_registry`:

```python
for key, val in POOCH.registry.items():
    if val == sentinel:
        POOCH.registry[key] = None
```

**suggestion**: Since the registry file lines *must* have 3 items in order to use a custom url,  would it be possible to have a sentinel value like `None` or `_` or something to indicate that the hash should be ignored?

```txt
# registry.txt
myfile.png None https://www.example.com/m9zyiek2kr9pbed/myfile.png
```

**Comment by leouieda** [comment]
Hi @tlambert03 thank you for the suggestion! Would this feature allow you personally to do something with Pooch that is currently not possible or very inconvenient? In other words, is this something that you currently need for a project?

I'm asking because I have a few reservations about adding this, so I'd avoid if unless there is a compelling reason and an immediate use case.

**Comment by tlambert03** [comment]
nah, totally fine with me to close this as "will not implement".  
personally, I can accomplish whatever I need by doing the very small correction in my OP.  thanks!

**Comment by leouieda** [comment]
Alright, I'll close this then. The registry files is causing us so many headaches recently that I'm considering ditching the entire thing to be honest. Really, we should have just made it a JSON file and used the `json` module to parse it...
