### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#39]
Pooch currently has no logo. I'm not the best designer and would really welcome any contributions or ideas on this front. A few requirements of the logo:

* Simple design with the minimum number of colors
* Look good in large and small sizes
* Work with dark or light backgrounds
* Square proportions (so it can work in a banner, profile picture, favicon, sticker, etc)

**Comment by jrleeman** [comment]
Maybe a job for someone on fiverr? Its amazing what people to do it daily can come up with quickly. That being said, something like this could be awesome: http://pluspng.com/png-147986.html

**Comment by leouieda** [comment]
Just had a look at fiverr. Thanks for point it out! I might give it a try. We need a new logo for GMT as well so this could be useful.
