### ISSUE TITLE
Ability to download specific folders rather than files?

### ISSUE THREAD

**Issue by JoeZiminski** [fatiando/pooch#422]
Hey, thanks for this very convenient tool!

I was wondering if it is possible to use pooch similarity to [downloading a single file](https://www.fatiando.org/pooch/latest/retrieve.html) but instead downloading a folder. So essentially the same command but rather than pointing to a single file, you can point to a single folder and download its entire contents. 

I took a look at the docs but couldnt see something similar, apologies if I have missed it! Our usecase is downloading files and folders from a GIN repository.

**Comment by leouieda** [comment]
Hi @JoeZiminski I had thought of that before but there's no way to do it reliably. There is no HTTP request that I know of that would give you a list of files in a folder on the server. The only hope is if the files are listed on an index page which can then be scrapped. But this will be unique per use case.

If there is a page in the server that lists all of the files that it contains, then I'd recommend using [Beautiful Soup](https://beautiful-soup-4.readthedocs.io/en/latest/) to get all of the file links from the webpage and then feed them to Pooch.

**Comment by JoeZiminski** [comment]
Thanks @leouieda, thats good to know!

**Comment by shaunc** [comment]
How about targets like s3 or sftp which do have directory structures? We would like to use pooch for zarr "files" but lack of dir support is a sumbling block as a zarr is actually a directory.

For a general url I could imagine globs or templates `https://the.ser.ver/path/to/the/dir/*.html`

**Comment by leouieda** [comment]
@shaunc we don't currently support s3 and don't plan to. We're actually thinking of removing the sftp support as well since it's a common source of maintenance issues. 

I'm not too familiar with zarr but are they always not a single file? Not even a zip or tar? Even with a glob like that it's not trivial to crawl the server to map it our and figure out what to download. That's beyond the scope of Pooch anyway.
