### ISSUE TITLE
Use the XDG_CACHE_HOME environment variable if it exists

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#43]
Following the discussion in #26, we need to make some changes to the `os_cache` function in [pooch/utils.py](https://github.com/fatiando/pooch/blob/master/pooch/utils.py) function to be compliant with the FreeDesktop standards:

* Add an option `check_environment` to the function that defaults to `False`
* If `check_environment == True`, check if the `XDG_CACHE_HOME` environment variable is defined.
* If it is, use it to define the default cache location instead of `~/.cache` on Linux.

**Comment by remram44** [comment]
I would rather have this be the default, since this is the correct behavior. Leaving it up to users of this library doesn't help, because it is really up to the end-users where that data should be (e.g. not in my backups). Hence the environment variable.

If someone really relies on the previous behavior, they should probably be the ones setting an argument or an environment variable.

**Comment by jrleeman** [comment]
I think I'm fine with it being the default behavior as well.

**Comment by leouieda** [comment]
:+1: OK, I don't mind either way. If it's the default, should we just not make it optional? Library devs can already set their own directories if they want and we provide a mechanism for setting this through environment variables.

**Comment by dopplershift** [comment]
I think it's enough to "just" do:
```python
mydir = os.environ.get('XDG_CACHE_HOME', os.path.expanduser(`~/.cache`))
```
or something similar.

**Comment by remram44** [comment]
That's right! Though a better option would be [`appdirs.user_cache_dir(project)`](https://pypi.org/project/appdirs/) :thinking:

**Comment by leouieda** [comment]
@remram44 if we're going with `appdirs` then maybe we can get rid of the `os_cache` function altogether (since that is what `appdirs` is doing). That way we don't have to depend on it directly and reduce our code base. We can recommend using the library in the documentation if you want to use the standard directories.

If that's the case, then #45 and #44 can be closed and replaced by a documentation change and deletion of `os_cache`.

@dopplershift https://github.com/ActiveState/appdirs/blob/master/appdirs.py#L92:

```python
path = os.getenv('XDG_DATA_HOME', os.path.expanduser("~/.local/share"))
```

Convergent evolution :laughing:

**Comment by leouieda** [comment]
OK, we're now using appdirs for `os_cache` and I'll probably keep it like that to avoid telling people to install something else. We can always vendor in their code is the dependency becomes an issue.
