### ISSUE TITLE
Check availability of remote files

### ISSUE THREAD

**Issue by santisoler** [fatiando/pooch#46]
## Feedback or description of feature requested

Would be nice to have a method inside `Pooch` to check if any file from the `registry` is available in the remote url. The idea is not to fetch the entire file, but only snoop if it's available for download (like `wget --spider` does).

This feature could help to build test functions involving `Pooch` objects in case of big files or huge registries. In some cases it's only necessary to test if the data is available online instead of downloading the entire set of files, what could take a lot of time.
Also, this feature could be a fast way to test if the host is up.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
:+1: that's a good suggestion @santisoler! How are you thinking of implementing this? There should be something in the `requests` package.
