### ISSUE TITLE
demo of preferrred way to get a hash value to match the one in remote for thousands of file.

### ISSUE THREAD

**Issue by JustinGOSSES** [fatiando/pooch#63]
Add example to readme of how to get a hash values to match ones in remote repo for thousands of files. Specifically, code you might run in the command line.

**Are you willing to help implement and maintain this feature?** Yes, test.

**Comment by leouieda** [comment]
Hi Justin, just copying in our discussion on Slack for the record:

We have a function that generates a registry file with the hashes for all files in a given directory (recursively): https://www.fatiando.org/pooch/latest/api/generated/pooch.make_registry.html#pooch.make_registry
It's in the tutorial: https://www.fatiando.org/pooch/latest/usage.html#creating-a-registry-file But it might be a bit hard to find now that you mention it.

**Comment by JustinGOSSES** [comment]
Thanks, got it working based on tutorial. 

Will circle around to this again after I've used Pooch for a while before.

**Comment by leouieda** [comment]
Thanks, Justin! Looking forward to the bug reports :)
