### ISSUE TITLE
Try using Pooch in Verde

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#7]
Try replacing the custom code in [Verde](https://github.com/fatiando/verde) with Pooch to see if we find any problems in the wild.

**Comment by leouieda** [comment]
@jrleeman I switched to using pooch in verde without any problems. I'm installing using pip for now. As soon as you're ready with #9 I can make a new alpha release to test it with MetPy. If that works then I'll get started on the conda package.

**Comment by jrleeman** [comment]
Hey @leouieda - hopefully we can close #9 and testing in metpy next week!

**Comment by leouieda** [comment]
@jrleeman no problem, take your time. I know you're busy :bee:
