### ISSUE TITLE
Re-enable Python 3.5 builds

### ISSUE THREAD

**Issue by leouieda** [fatiando/pooch#92]
**Description of the desired feature**

Scikit-image is looking into using Pooch (scikit-image/scikit-image#3945) but they need Python 3.5 still. The code works under 3.5 so there aren't any changes needed to get this working. It's mostly a matter of setting `python_requires` in `setup.py` and enabling the CI builds of 3.5. 

The problem is that we won't be able to build packages for conda-forge since Pooch isn't a `noarch` package there (because of extra dependencies required for 2.7).

Pinging @stefanv @hmaarrfk. Is this something worth pursuing?

**Comment by hmaarrfk** [comment]
Let's leave conda forge to their agressive updates. We are more interested in LTS platforms with support for 3.5. those mostly use pip.

Pooch will only make it on 3+ platforms for scikit-image

**Comment by leouieda** [comment]
@hmaarrfk OK, I'll try to get a 3.5 build working again and a new minor release

**Comment by leouieda** [comment]
@hmaarrfk version 0.5.2 is up on PyPI now and is compatible with 3.5: https://pypi.org/project/pooch/0.5.2/

**Comment by hmaarrfk** [comment]
Whoa. So cool. Thanks.
